// Generate a random code of 5 char


// Creates a name for a user, "Anonymous <random animal name>"
export const generateRandomName = () => {
  const animals = [
    "Dog",
    "Cat",
    "Rat",
    "Bat",
    "Elephant",
    "Hamster",
    "Dragon",
    "Giraffe",
    "Chinchilla",
    "Axolotl",
    "Cheetah",
    "Liger",
    "Tiger",
    "Lion",
    "Badger",
    "Possum",
    "Dire wolf",
    "Raven",
    "Racoon",
    "Panda",
    "Cockatiel",
    "Toucan",
    "Crane",
    "Frog",
    "Spider",
    "Rabbit",
    "Hare",
    "Bear",
    "Deer",
    "Horse",
    "Squirrel",
    "Mouse",
    "Boar",
    "Fox",
    "Owl",
    "Butterfly",
    "Jaguar",
    "Boa",
    "Peacock",
    "Antelope",
    "Leopard",
    "Polar bear",
    "Crocodile",
    "Pistol shrimp",
    "Eagle",
    "Magpie",
    "Whale",
    "Swan",
    "Bobcat",
    "Rattlesnake",
    "Zebra",
    "Vulture",
    "Koala",
    "Shark",
    "Octopus",
    "Squid",
    "Crab",
    "Cuttlefish",
    "Hedgehog",
    "Lizard",
    "Wildebeest",
    "Buffalo",
    "Warthog",
    "Bison",
    "Impala",
    "Pheasant",
    "Mole",
    "Chameleon",
    "Guinea pig",
    "Capybara",
    "Kangaroo",
    "Penguin",
    "Monkey",
    "Ape",
    "Snail",
    "Sandworm",
    "Jellyfish",
    "Sea Cucumber",
    "Moth",
    "Crow",
    "Donkey",
    "Wallaby",
    "Starfish",
    "Hyena",
    "Boobie",
    "Robin",
    "Hippo",
    "Rhino",
    "Cougar",
    "Cow",
    "Turtle",
    "Dingo",
    "Flamingo",
    "Coyote",
    "Fennec fox",
    "Dragon fly",
    "Porcupine",
    "Condor",
    "Kiwi",
    "Emu",
  ]
  return `Anonymous ${animals[Math.floor(Math.random() * animals.length)]}`
}
